[server]
headless = true
enableCORS = false

# REMOVE this line to let Streamlit pick the port automatically.
# OR set a default integer port like below:
# port = 8501

[theme]
primaryColor = "#00BFFF"
backgroundColor = "#0f1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"
